node {
  environment {
         registry = "Angulartest"
        registryCredential = 'locrepcred'
        dockerImage = ''
        def nodeHome = tool 'node8'
    env.PATH = "${nodeHome}/bin:${env.PATH}"
            }
      
    stage ('checkout'){
      
        checkout scm
      
    }
    stage ('install modules'){
      
        sh '''
          npm install --verbose -d 
          npm install --save classlist.js
        '''
      
    }
    stage ('test'){
      
        sh '''
          $(npm bin)/ng test --single-run --browsers Chrome_no_sandbox
        '''
           junit "test-results.xml"
      
    }
    stage ('code quality'){
      
        sh '$(npm bin)/ng lint'
      
    }
    stage ('build') {
      
        sh '$(npm bin)/ng build --prod --build-optimizer'
     
    }
  stage  ('docker image') {
    
     script {
        registry = "Angulartest"
        registryCredential = 'locrepcred'
        dockerImage = ''
                dockerImage =  docker.build registry  
     }
       
       stage ('push to local-repo') {
              registry = "Angulartest"
              registryCredential = 'locrepcred'
                script {
                  docker.withRegistry ('http://192.168.5.64:5000',registryCredential) { 
                  dockerImage.push()
                  }
    
      }
  }
  }
}
